dist: trusty
sudo: false
language: php
php: 
  - '5.6'
  - '7.2'
addons:
    github_token:
      secure: "PDqe9CZLDdUkGfyIx29Mc4AD9X1sKwiNxUK2IQWkvWNIQHD0v87obZRXxWqisbJ7KLEui9Gee14bPvYJYc03oMlzOp1HMr87TENMEsuFPIzh5OG13TtdyvRnVYTKo24vBQ27F2UWvJvZlo0wfR2RBVILtdsCErYaF+2Ryd7EocFR8JcVeLQchtD+z1pyM5876tfqBZ8XpVe2Uf3sl49yR6yJkgCiGyLbNFWYl3fcSbSZy8kwatlH0SovkkPoYWvVRJJT+dzRVMUO4uCO3TZs48QSnn8x7bqR7GhMLdE9WS94UaK9zTNhH3VTJsUdVVY4phW7SbgAHu4rfPoe4pp2TFnlF5CDyHXPq7LnR9gzEwjFUiYMv4d5i73/xUZw002aOGnikLp2KO+lN445+1HMiHZrn4rV/grWBhPTuAMKM351X2wHF56HX8dUdXYPvJwi4B78hDn1FoTOBgcuq14GHEnLqjkDb/LFdZ4PHtfKsvYtOUhEjMf8RkGQWHeN/2dPqzxJiOW+nOrDS2AADY7K6faeG4ZM0EsaClTmzPHz+AiAC6R5Lv+kcRYRguRg+rdpL0UlWm36uY7TJxCl5sZQLPpwRxE3S7GdRzsfh1JP0p0i36AC8sXdKXjT6BCo7lluOI29Z8IcpvNDcnltlmY18+WSdBRrzGVPLl0XUipADFA="

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

script:
  - composer cs-check
  
before_deploy:
  - bash .bin/generate-release-package.sh $TRAVIS_TAG
  - ls -lah target

deploy:
  provider: releases
  api_key:
    secure: BOCYBPIqK0gpRmPf34Nj2nOWjpqEO7s63AKw0Ct/sN6MPaaIX/Op/REJMx4jTj74QpSRKNfaKsn4a2IL42eh96H3fJJp8nRXoycwC9EK4SFF53PxOn6VuSpvyAqTYash5efmlmFQgxYfEsqZbuT9ogPVfHKwIQRyOZkERXCX+pEYsGnNW7K0gw/2X5wSgSXvEtTW58sh4K1ewJQpUXTxgN9B72Kcu9nZuLckusWuKle/4rhfmMX284Hel8DsjA55ENg6CtrCeQR16RYMDs/+J7LwStonByDVXYhi4frPL5SB5/MFXzi3qHDMMp9WV1ihrNT0ho5rMgcZwReiFdCVEsTN3mVAIYhuGtKWkAIP3JHzv4prONEeBv66drr6l/OOBkeB1V0QCm9c+dvDiDbvAt7GMh6Jtq8nsEmue421GUcsWLwTa01iROkyfEAkmidKZULMDjUArVrcEwd1Gxd2v4mXQGJkJepGOOjZi/FbnPHGoZ9KaBm4IX5b52CjrMeg+JHxEKv8dvUGl1lZULYMrkRuLbAyrUsuEodyygYliY6sJUFPCjsuEYumw3N6yEkn2+c2WZjsbB7Igv0F/B6kRItUR7TIQvR7svioJaaydHf6dFFOBh8rrcDvmOimB7vvIRr0cmkyAH2PvW5/uYFqcr17epU3c0ZV7nhApoVOeSM=
  file: target/wpp-integration-demo-php-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: wirecard/wpp-integration-demo-php
    tags: true
